#!/bin/bash

# -- Cmd Werk Config --
# CMDW_GROUP_NAME='git'
# CMDW_HELP_BEGIN
# Auto commit dir and push in dev.
#
# CMDW_HELP_END

echo "Changes -- "
git diff --cached --exit-code
git commit -m"Change to be squashed @ $(date '+%Y:-%m-%d %H:%M')"
git push


