#!/bin/bash

# -- Cmd Werk Config --
# CMDW_GROUP_NAME='aws & ssh'
# CMDW_HELP_BEGIN
# Lists the ssh keyfiles.
# CMDW_HELP_END


pushd  ~/.ssh > /dev/null

# -- Color codes --
black=0; red=1; green=2; yellow=3; blue=4; magenta=5; cyan=6; white=7;
# -- No color codes --
# black=8; red=8; green=8; yellow=8; blue=8; magenta=8; cyan=8; white=8;

function color {
    if [ "$1" = "8" ]; then
        : # do nothing
    elif [ "$#" -ne 1 ]; then
        # reset color if no param.
        echo -n `tput sgr0`
    else
        echo -n `tput setaf $1`
    fi
}


color $yellow
echo "SSH Key files:"
# TMP_FILE=$(mktemp)

color $magenta
ls -1 ./*.pub
ls -1 ./*.pem


popd > /dev/null

