#
# Make file for creating documentation.
#
# Params .
SPHINX_OPTS    =
SPHINX_BUILD   = sphinx-build
SOURCE_DIR     = source
BUILD_DIR      = build

%: Makefile
	@$(SPHINX_BUILD) -M $@ "$(SOURCE_DIR)" "$(BUILD_DIR)" $(SPHINX_OPTS) $(O)